palikohrnne-web-app/Controllers/ProfilController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using palikohrnne_web_app.Api;
using palikohrnne_web_app.Extensions;
using palikohrnne_web_app.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace palikohrnne_web_app.Controllers
{
    public class ProfilController : Controller
    {
        private readonly CubesService _cubesService;

        public ProfilController(CubesService cubesService)
        {
            _cubesService = cubesService;
        }
        [Authorize]
        public async Task<IActionResult> Profil(int id)
        {
            var citoyen = await _cubesService.Authorize(User).GetCitoyenById(id);
            var userConnected = Int32.Parse(User.FindFirst("ID").Value);
            if (userConnected != citoyen.ID)
            {
                var relationsCible = await _cubesService.Authorize(User).GetRelationCitoyenIn(userConnected);
                ViewBag.DemandeRelation = relationsCible.Where(x => 
                x.CitoyenID == citoyen.ID &&
                x.CitoyenCibleID == userConnected && 
                !x.Approbation.HasValue).Any();
                if(ViewBag.DemandeRelation == true)
                {
                    ViewBag.TypeRelationId = relationsCible.First().TypeRelationID;
                }
                
            }
            return View(citoyen);
        }

        [Authorize]
        public async Task<IActionResult> ProfilPerso(int id)
        {
            var citoyen = await _cubesService.Authorize(User).GetCitoyenById(id);
            return View(citoyen);
        }

        [HttpPost]
        [Authorize]
        public async Task<IActionResult> SelfDetailAsync(Citoyen citoyen)
        {
            var selfId = Int32.Parse(User.FindFirst("ID").Value);
            var citoyenConnected = await _cubesService.Authorize(User).GetCitoyenById(selfId);

            Citoyen modifiedCitoyen = new()
            {
                ID = selfId,
                CreatedAt = citoyenConnected.CreatedAt,
                UpdatedAt = citoyenConnected.UpdatedAt,
                DeletedAt = citoyenConnected.DeletedAt,
                Adresse = citoyen.Adresse,
                CodePostal = citoyen.CodePostal,
                Genre = citoyen.Genre,
                Mail = citoyen.Mail,
                MotDePasse = citoyen.MotDePasse,
                Nom = citoyen.Nom,
                Prenom = citoyen.Prenom,
                Pseudo = citoyen.Pseudo,
                Telephone = citoyen.Telephone,
                Ville = citoyen.Ville,
                RangID = citoyenConnected.RangID
            };

            await _cubesService.UpdateCitoyen(modifiedCitoyen);
            return View();
        }

    }
}

palikohrnne-web-app/Controllers/RelationController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using palikohrnne_web_app.Api;
using palikohrnne_web_app.Extensions;
using palikohrnne_web_app.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

namespace palikohrnne_web_app.Controllers
{
    [Authorize]
    public class RelationController : Controller
    {
        private readonly CubesService _cubeService;
        public RelationController(CubesService cubesService)
        {
            _cubeService = cubesService;
        }

        public async Task<IActionResult> Index()
        {
            int userId = Int32.Parse(((ClaimsIdentity)User.Identity).GetSpecificClaim("ID"));

            IEnumerable<RelationCitoyen> relations = await _cubeService.Authorize(User).GetRelation(userId);
            IEnumerable<RelationCitoyen> inRelations = await _cubeService.Authorize(User).GetRelationCitoyenIn(userId);


            return View(new RelationsModel
            {
                Relations = relations.Where(x => x.Approbation == true).ToList(),
                InRelation = inRelations.Where(x => !x.Approbation.HasValue).ToList()
            });
        }
        [Authorize] 
        public async Task<IActionResult> Ajouter()
        {
            ViewBag.TypeRelation = new SelectList(await _cubeService.GetAllTypeRelations(), "ID", "Nom");
            return View(new RelationCitoyen { 
                CitoyenID = Int32.Parse(((ClaimsIdentity)User.Identity).GetSpecificClaim("ID"))
            });
        }
        [Authorize]
        [HttpPost]
        public async Task<IActionResult> Ajouter(RelationCitoyen relation)
        {
            await _cubeService.Authorize(User).AjouterRelation(relation);

            return RedirectToAction("Index");
        }

        [Authorize]
        public async Task<IActionResult> DecisionRelation(string decision, int idCitoyen, int typeRelationId)
        {
            int userId = Int32.Parse(((ClaimsIdentity)User.Identity).GetSpecificClaim("ID"));

            await _cubeService.Authorize(User).UpdateRelation(new RelationCitoyen
            {
                Approbation = decision == "Accepter",
                CitoyenCibleID = userId,
                CitoyenID = idCitoyen
            });

            await _cubeService.Authorize(User).AjouterRelation(new RelationCitoyen
            {
                Approbation = true,
                CitoyenCibleID = idCitoyen,
                CitoyenID = userId,
                TypeRelationID = typeRelationId
            });

            return RedirectToAction("Index", "Relation");
        }

        public async Task<IActionResult> SearchCitoyen(string search = "")
        {
            int userID = Int32.Parse(((ClaimsIdentity)User.Identity).GetSpecificClaim("ID"));
            var citoyens = await _cubeService.GetAllCitoyens();
            var result = citoyens
                .Where(x => x.Nom.StartsWith(search) || x.Prenom.StartsWith(search) || x.Pseudo.StartsWith(search))
                .Where(x => x.ID != userID);
            return Json(new
            {
                results =
                result.Select(x => new
                {
                    id = x.ID,
                    text = x.Nom + " " + x.Prenom + " ("  + x.Pseudo +  ") "
                }).ToList()
            }); ;
        }
    }
}

palikohrnne-web-app/Views/Relation/Ajouter.cshtml
@model RelationCitoyen
@{
    ViewData["Title"] = "Ajouter";
}
@section Styles {
    <link href="~/lib/select2/css/select2.css" rel="stylesheet" />
}
@section Scripts{
    <script src="~/lib/select2/js/select2.js"></script>
    <script src="~/lib/select2/js/i18n/fr.js"></script>
    <script src="~/js/select2Relation.js"></script>
}

<h1 class="app-page-title">Ajouter une relation</h1>
<hr class="mb-4">
<div class="row g-4 settings-section">
    <div class="col-12 col-md-8 mx-auto">
        <div class="app-card app-card-settings shadow-sm p-4">

            <div class="app-card-body">
                <form asp-action="Ajouter" method="post" class="settings-form">
                    <input type="hidden" asp-for="CitoyenID">
                    <div class="mb-3">
                        <label for="setting-input-2" class="form-label">Nom, prénom ou pseudo du citoyen</label>
                        <select asp-for="CitoyenCibleID" class="form-control" id="select2-relation"></select>
                    </div>
                    <div class="mb-3">
                        <label for="setting-input-3" class="form-label">Business Email Address</label>
                        <select asp-for="TypeRelationID" class="form-control" asp-items="ViewBag.TypeRelation"></select>
                    </div>
                    <button type="submit" class="btn app-btn-primary">Ajouter</button>
                </form>
            </div><!--//app-card-body-->

        </div><!--//app-card-->
    </div>
</div><!--//row-->

palikohrnne-web-app/Views/Relation/Index.cshtml
@model RelationsModel
@{
    ViewData["Title"] = "Index";

    string BadgeRangClasse(string rang)
    {
        string badgeClasse = "bg-success";
        switch (rang)
        {
            case "Ami":
                {
                    badgeClasse = "bg-success";
                    break;
                }
            case "Collègue":
                {
                    badgeClasse = "bg-warning";
                    break;
                }
            case "Famille":
                {
                    badgeClasse = "bg-danger";
                    break;
                }
            default:
                {
                    badgeClasse = "bg-dark";
                    break;
                }
        }
        return badgeClasse;
    }
}



<div class="row g-3 mb-4 align-items-center justify-content-between">
    <div class="col-auto">
        <h1 class="app-page-title mb-0">Relations</h1>
    </div>
</div><!--//row-->


<nav id="orders-table-tab" class="orders-table-tab app-nav-tabs nav shadow-sm flex-column flex-sm-row mb-4">
    <a class="flex-sm-fill text-sm-center nav-link active" id="orders-all-tab" data-toggle="tab" href="#orders-all" role="tab" aria-controls="orders-all" aria-selected="true">Tous</a>
    <a class="flex-sm-fill text-sm-center nav-link" id="orders-paid-tab" data-toggle="tab" href="#orders-paid" role="tab" aria-controls="orders-paid" aria-selected="false">Collègues</a>
    <a class="flex-sm-fill text-sm-center nav-link" id="orders-pending-tab" data-toggle="tab" href="#orders-pending" role="tab" aria-controls="orders-pending" aria-selected="false">Famille</a>
    <a class="flex-sm-fill text-sm-center nav-link" id="orders-cancelled-tab" data-toggle="tab" href="#orders-cancelled" role="tab" aria-controls="orders-cancelled" aria-selected="false">Amis</a>
    <a class="flex-sm-fill text-sm-center nav-link" id="demandes-tab" data-toggle="tab" href="#demandes" role="tab" aria-controls="orders-cancelled" aria-selected="false">
        Demandes de relation
        @if (Model.InRelation.Where(x => !x.Approbation.HasValue).Any())
        {
            <span class="badge bg-danger">@Model.InRelation.Where(x => !x.Approbation.HasValue).Count()</span>
        }

    </a>
</nav>


<div class="tab-content" id="orders-table-tab-content">
    <div class="tab-pane fade show active" id="orders-all" role="tabpanel" aria-labelledby="orders-all-tab">
        <div class="app-card app-card-orders-table shadow-sm mb-5">
            <div class="app-card-body">
                <div class="table-responsive">
                    <table class="table app-table-hover mb-0 text-left">
                        <thead>
                            <tr>
                                <th class="cell">Nom et prénom</th>
                                <th class="cell">Pseudo</th>
                                <th class="cell">Type de relation</th>
                                <th class="cell"></th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var relation in Model.Relations)
                            {
                                <tr>
                                    <td class="cell"><span class="truncate">@relation.CitoyenCible.Nom @relation.CitoyenCible.Prenom</span></td>
                                    <td class="cell">@relation.CitoyenCible.Pseudo</td>
                                    <td class="cell"><span class="badge @BadgeRangClasse(relation.TypeRelation.Nom)">@relation.TypeRelation.Nom</span></td>
                                    <td class="cell"><a class="btn-sm app-btn-secondary" asp-controller="Profil" asp-action="Profil" asp-route-id="@relation.CitoyenCibleID">Voir</a></td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div><!--//table-responsive-->

            </div><!--//app-card-body-->
        </div><!--//app-card-->
    </div><!--//tab-pane-->

    <div class="tab-pane fade" id="orders-paid" role="tabpanel" aria-labelledby="orders-paid-tab">
        <div class="app-card app-card-orders-table mb-5">
            <div class="app-card-body">
                <div class="table-responsive">
                    <table class="table app-table-hover mb-0 text-left">
                        <thead>
                            <tr>
                                <th class="cell">Nom et prénom</th>
                                <th class="cell">Pseudo</th>
                                <th class="cell">Type de relation</th>
                                <th class="cell"></th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var relation in Model.Relations.Where(x => x.TypeRelation.Nom == "Collègue"))
                            {
                                <tr>
                                    <td class="cell"><span class="truncate">@relation.CitoyenCible.Nom @relation.CitoyenCible.Prenom</span></td>
                                    <td class="cell">@relation.CitoyenCible.Pseudo</td>
                                    <td class="cell"><span class="badge @BadgeRangClasse(relation.TypeRelation.Nom)">@relation.TypeRelation.Nom</span></td>
                                    <td class="cell"><a class="btn-sm app-btn-secondary" asp-controller="Profil" asp-action="Profil" asp-route-id="@relation.CitoyenCibleID">Voir</a></td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div><!--//table-responsive-->
            </div><!--//app-card-body-->
        </div><!--//app-card-->
    </div><!--//tab-pane-->

    <div class="tab-pane fade" id="orders-pending" role="tabpanel" aria-labelledby="orders-pending-tab">
        <div class="app-card app-card-orders-table mb-5">
            <div class="app-card-body">
                <div class="table-responsive">
                    <table class="table app-table-hover mb-0 text-left">
                        <thead>
                            <tr>
                                <th class="cell">Nom et prénom</th>
                                <th class="cell">Pseudo</th>
                                <th class="cell">Type de relation</th>
                                <th class="cell"></th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var relation in Model.Relations.Where(x => x.TypeRelation.Nom == "Famille"))
                            {
                                <tr>
                                    <td class="cell"><span class="truncate">@relation.CitoyenCible.Nom @relation.CitoyenCible.Prenom</span></td>
                                    <td class="cell">@relation.CitoyenCible.Pseudo</td>
                                    <td class="cell"><span class="badge @BadgeRangClasse(relation.TypeRelation.Nom)">@relation.TypeRelation.Nom</span></td>
                                    <td class="cell"><a class="btn-sm app-btn-secondary" asp-controller="Profil" asp-action="Profil" asp-route-id="@relation.CitoyenCibleID">Voir</a></td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div><!--//table-responsive-->
            </div><!--//app-card-body-->
        </div><!--//app-card-->
    </div><!--//tab-pane-->
    <div class="tab-pane fade" id="orders-cancelled" role="tabpanel" aria-labelledby="orders-cancelled-tab">
        <div class="app-card app-card-orders-table mb-5">
            <div class="app-card-body">
                <div class="table-responsive">
                    <table class="table app-table-hover mb-0 text-left">
                        <thead>
                            <tr>
                                <th class="cell">Nom et prénom</th>
                                <th class="cell">Pseudo</th>
                                <th class="cell">Type de relation</th>
                                <th class="cell"></th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var relation in Model.Relations.Where(x => x.TypeRelation.Nom == "Ami"))
                            {
                                <tr>
                                    <td class="cell"><span class="truncate">@relation.CitoyenCible.Nom @relation.CitoyenCible.Prenom</span></td>
                                    <td class="cell">@relation.CitoyenCible.Pseudo</td>
                                    <td class="cell"><span class="badge @BadgeRangClasse(relation.TypeRelation.Nom)">@relation.TypeRelation.Nom</span></td>
                                    <td class="cell"><a class="btn-sm app-btn-secondary" asp-controller="Profil" asp-action="Profil" asp-route-id="@relation.CitoyenCibleID">Voir</a></td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div><!--//table-responsive-->
            </div><!--//app-card-body-->
        </div><!--//app-card-->
    </div><!--//tab-pane-->
    <div class="tab-pane fade" id="demandes" role="tabpanel" aria-labelledby="orders-cancelled-tab">
        <div class="app-card app-card-orders-table mb-5">
            <div class="app-card-body">
                <div class="table-responsive">
                    <table class="table app-table-hover mb-0 text-left">
                        <thead>
                            <tr>
                                <th class="cell">Nom et prénom</th>
                                <th class="cell">Pseudo</th>
                                <th class="cell">Type de relation</th>
                                <th class="cell"></th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var relation in Model.InRelation.Where(x => !x.Approbation.HasValue))
                            {
                                <tr>
                                    <td class="cell"><span class="truncate">@relation.Citoyen.Nom @relation.Citoyen.Prenom</span></td>
                                    <td class="cell">@relation.Citoyen.Pseudo</td>
                                    <td class="cell"><span class="badge @BadgeRangClasse(relation.TypeRelation.Nom)">@relation.TypeRelation.Nom</span></td>
                                    <td class="cell"><a class="btn-sm app-btn-secondary" asp-controller="Profil" asp-action="Profil" asp-route-id="@relation.Citoyen.ID">Voir</a></td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div><!--//table-responsive-->
            </div><!--//app-card-body-->
        </div><!--//app-card-->
    </div><!--//tab-pane-->
</div><!--//tab-content-->